# Fichier: kairn/docker-compose.yml (Version Finale)

services:
  # Service de la base de données PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: kairn_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Service du cache Redis
  redis:
    image: redis:7-alpine
    container_name: kairn_redis
    ports:
      - "6379:6379"

  # Service du backend FastAPI
  backend:
    build:
      context: ./backend
    container_name: kairn_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    # Le point d'entrée est notre script, qui lance ensuite uvicorn
    command: /app/prestart.sh uvicorn app.main:app --host 0.0.0.0 --port 8000

  # Service du frontend Next.js
  frontend:
    build:
      context: ./frontend
    container_name: kairn_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # LA COMMANDE CORRECTE POUR LE FRONTEND
    command: npm run dev
    
volumes:
  postgres_data: